"""Add tag_name to company_tags and institution_tags

Revision ID: 3bb32bd42f11
Revises: 4be33d3d48ac
Create Date: 2025-08-11 22:38:06.967290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bb32bd42f11'
down_revision = '4be33d3d48ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag_name', sa.String(length=120), nullable=False))

    with op.batch_alter_table('institution_tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag_name', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('institution_tags', schema=None) as batch_op:
        batch_op.drop_column('tag_name')

    with op.batch_alter_table('company_tags', schema=None) as batch_op:
        batch_op.drop_column('tag_name')

    # ### end Alembic commands ###
