"""empty message

Revision ID: 663d9f3005c8
Revises: c2d940eff900
Create Date: 2025-08-10 20:07:58.500584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '663d9f3005c8'
down_revision = 'c2d940eff900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
