"""Add uniqueness constraints to tags

Revision ID: 8582148ec18b
Revises: 3bb32bd42f11
Create Date: 2025-08-11 23:01:42.302717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8582148ec18b'
down_revision = '3bb32bd42f11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_tags', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_company_tag', ['company_id', 'tag_name'])

    with op.batch_alter_table('institution_tags', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_institution_tag', ['institution_id', 'tag_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('institution_tags', schema=None) as batch_op:
        batch_op.drop_constraint('unique_institution_tag', type_='unique')

    with op.batch_alter_table('company_tags', schema=None) as batch_op:
        batch_op.drop_constraint('unique_company_tag', type_='unique')

    # ### end Alembic commands ###
